apiVersion: apps/v1
kind: Deployment
metadata:
  name: agegate-verifier
  labels:
    app: agegate-verifier
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agegate-verifier
  template:
    metadata:
      labels:
        app: agegate-verifier
    spec:
      containers:
      - name: verifier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
