apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agegate-verifier
  labels:
    app: agegate-verifier
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agegate-verifier
            port:
              number: {{ .Values.service.port }}
