apiVersion: v1
kind: Secret
metadata:
  name: agegate-secrets
type: Opaque
stringData:
  ADMIN_PASS: "{{ .Values.env.ADMIN_PASS | default "change-me-in-prod" }}"
  TIMESCALEDB_PASSWORD: "{{ .Values.env.TIMESCALEDB_PASSWORD }}"
  REDIS_PASSWORD: "{{ .Values.env.REDIS_PASSWORD | default "" }}"
