apiVersion: v1
kind: Secret
metadata:
  name: agegate-secrets
type: Opaque
stringData:
  ADMIN_PASS: "{{ .Values.secrets.ADMIN_PASS | required "ADMIN_PASS is required" }}"
  TIMESCALEDB_PASSWORD: "{{ .Values.secrets.TIMESCALEDB_PASSWORD | required "TIMESCALEDB_PASSWORD is required" }}"
  REDIS_PASSWORD: "{{ .Values.env.REDIS_PASSWORD | default "" }}"
  SESSION_SECRET: "{{ .Values.secrets.SESSION_SECRET | required "SESSION_SECRET is required" }}"
  SMTP_USER: "{{ .Values.secrets.SMTP_USER | default "" }}"
  SMTP_PASS: "{{ .Values.secrets.SMTP_PASS | default "" }}"
  STRIPE_SECRET_KEY: "{{ .Values.secrets.STRIPE_SECRET_KEY | default "" }}"
  STRIPE_WEBHOOK_SECRET: "{{ .Values.secrets.STRIPE_WEBHOOK_SECRET | default "" }}"
  IP_SALT: "{{ .Values.secrets.IP_SALT | default "" }}"
