{{- if .Values.privacy.ipSalt.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agegate-verifier.fullname" . }}-ip-salt
  labels:
    {{- include "agegate-verifier.labels" . | nindent 4 }}
type: Opaque
data:
  ip-salt: {{ .Values.privacy.ipSalt.value | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
