mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.116.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

useGOMEMLIMIT: true

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8889"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      namespace: agegate
    debug:
      verbosity: basic

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [prometheus, debug]
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]   # Change to otlphttp if Tempo is used
